#lang racket
(require "bmrkdef.rkt") 

(provide load-db)

(define (load-db)

(b “Category Theory, The essence of interface-based design - Erik Meijer” (u “https://m.youtube.com/watch?v=JMP6gI5mLHc”) '(cs category-theory video) “”)
  (b "BGP View" (u "https://bgpview.io/") '(internet data) "information about ASNs, for example: https://bgpview.io/asn/11830")
  (b "Hurricane Electric Internet Services" (u "https://bgp.he.net/exchange/CRIX") '(internet data) ":)")
  (b "Internet Exchange Point Datasets" (u "https://www.pch.net/ixp/data") '(internet data) "")
  (b "CAIDA Internet eXchange Points (IXPs) Dataset" (u "https://www.caida.org/data/ixps/") '(internet data) "")
  (b "University of Oregon Route Views Project" (u "http://www.routeviews.org/routeviews/") '(internet bgp information) "")
  (b "Anatomy of Modules in Go" (u "https://medium.com/rungo/anatomy-of-modules-in-go-c8274d215c16") '(go) "")
  (b "CH340 driver" (u "https://cdn.sparkfun.com/assets/learn_tutorials/5/9/7/") '(sofware electronics) "")
  (b "Getting Started with ESP8266 (ESP-01) module | How to program ESP-01 module" (u "https://www.youtube.com/watch?v=uqx2Z4bWjOs") '(video electronics howto) "")
  (b "ESP8266 Serial WIFI Module" (u "https://www.itead.cc/wiki/ESP8266_Serial_WIFI_Module") '(electronics specs) "at commands, schematics")
  (b "Best Practices for using NeoPixels" (u "https://learn.adafruit.com/adafruit-neopixel-uberguide/best-practices") '(electronics howto neopixels) "")
  (b "A Beginner's Guide to the ESP8266" (u "https://tttapa.github.io/ESP8266/Chap01%20-%20ESP8266.html") '(book electronics howto) "super complete")
  (b "Deep Space One" (u "https://somafm.com/deepspaceone/index.html") '(music ambient electronic) "")
  (b "The Hypnotic World of Degenerate Spirals" (u "https://www.dogatekin.com/blog/hypnotic-degenerate-spirals/") '(generative-art) "")
  (b "PDF generation in Go" (u "https://github.com/jung-kurt/gofpdf") '(go libraries pdf) "")
  (b "Barcode generation in Go" (u "https://github.com/boombuler/barcode/") '(go barcodes libraries) "")
  (b "Markdown parser in Go" (u "https://github.com/yuin/goldmark") '(go parsers markdown) "playing a little with an extension: https://github.com/DuqueDeTuring/bookmarksexperiment")
  (b "SETTING UP POSTGRESQL STREAMING REPLICATION" (u "https://www.cybertec-postgresql.com/en/setting-up-postgresql-streaming-replication/") '(howto postgres) "")
  (b "Ursula K. Le Guin" (u "https://www.ursulakleguin.com/home/") '(watchdog ❤) "web home")
  (b "Category Theory" (u "https://plato.stanford.edu/entries/category-theory/") '(sep category-theory cs) "")
  (b "dmitry.gr"(u "https://dmitry.gr") '(electronics re blog watchdog) "")
  (b "Saleae Logic" (u "https://www.saleae.com/") '(products electronics re) "logic analyzer recommended in https://dmitry.gr/?r=05.Projects&proj=30.%20Reverse%20Engineering%20an%20Unknown%20Microcontroller")
  (b "gofeed" (u "https://github.com/mmcdole/gofeed") '(code rss github go) "rss feed reader in go")
  (b "Send My: Arbitrary data transmission via Apple's Find My network" (u "https://positive.security/blog/send-my") '(re protocols privacy security article) "")
  (b "3 Simple Ways of Programming an ESP8266 12X Module" (u "https://www.instructables.com/3-Simple-Ways-of-Programming-an-ESP8266-12X-Module/") '(electronics howto) "")
  (b "Getting Started with ESP8266 WiFi Transceiver (Review)" (u "https://randomnerdtutorials.com/getting-started-with-esp8266-wifi-transceiver-review/") '(electronics howto) "")
  (b "How to Flash ESP-01 Firmware to the Improved SDK v2.0.0" (u "https://www.allaboutcircuits.com/projects/flashing-the-ESP-01-firmware-to-SDK-v2.0.0-is-easier-now/") '(electronics howto) "")
  (b "Category Theory: Lecture Notes And Online Books" (u "https://www.logicmatters.net/categories/") '(cs category-theory) "")
  (b "Terminal and initial objects 1" (u "https://youtu.be/yeQcmxM2e5I") '(cs category-theory video) "")
  (b "Category theory for the working hacker by Philip Wadler" (u "https://youtu.be/V10hzjgoklA") '(cs category-theory video ❤) ""))